# Generated by Django 2.1.7 on 2019-03-08 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JiraSetup',
            fields=[
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SasSActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'SasS Actions',
            },
        ),
        migrations.CreateModel(
            name='SasSSheetMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.CharField(max_length=100)),
                ('jira_actions', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jira.SasSActions', unique=True)),
            ],
            options={
                'verbose_name_plural': 'SasS SheetMap',
            },
        ),
        migrations.CreateModel(
            name='SheetActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sheet Actions',
            },
        ),
        migrations.AddField(
            model_name='sasssheetmap',
            name='sheet_actions',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jira.SheetActions'),
        ),
        migrations.AddField(
            model_name='sasssheetmap',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
