# Generated by Django 2.1.7 on 2019-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasssheetmap',
            name='worksheet_id',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
