# Generated by Django 2.1.7 on 2019-03-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0005_auto_20190309_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='sassactions',
            name='app',
            field=models.CharField(default='Jira', max_length=10),
        ),
    ]
