# Generated by Django 2.1.7 on 2019-03-13 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('used_in', models.IntegerField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Connections',
            },
        ),
    ]
