# Generated by Django 2.1.7 on 2019-03-10 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spreadsheet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=100)),
                ('api_column', models.CharField(max_length=20)),
                ('sheet_column', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SasSActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(default='Jira', max_length=10)),
                ('action', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'SasS Actions',
            },
        ),
        migrations.CreateModel(
            name='SasSSheetMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(default='Jira', max_length=10)),
                ('sheet_id', models.CharField(max_length=100, null=True)),
                ('worksheet_id', models.IntegerField(default=0, max_length=3)),
                ('sass_actions', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sass_sheet.SasSActions', unique=True)),
                ('sheet_actions', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='spreadsheet.SheetActions')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SasS SheetMap',
            },
        ),
    ]
