# Generated by Django 2.1.7 on 2019-03-10 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sasssheetmap',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
