# Generated by Django 2.1.7 on 2019-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass_sheet', '0002_auto_20190310_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sasssheetmap',
            name='sheet_id',
            field=models.CharField(default='none', max_length=100, null=True, unique=True),
        ),
    ]
