# Generated by Django 2.1.7 on 2019-03-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass_sheet', '0004_auto_20190310_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasssheetmap',
            name='api_columns',
            field=models.ManyToManyField(to='sass_sheet.ApiField'),
        ),
        migrations.AlterField(
            model_name='sasssheetmap',
            name='sheet_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
