# Generated by Django 2.1.7 on 2019-03-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass_sheet', '0006_auto_20190311_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sasssheetmap',
            name='api_columns',
            field=models.ManyToManyField(null=True, to='sass_sheet.ApiField'),
        ),
    ]
