# Generated by Django 2.1.7 on 2019-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass_sheet', '0007_auto_20190311_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sassactions',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
