# Generated by Django 2.1.7 on 2019-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass_sheet', '0008_auto_20190311_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sassactions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
