# Generated by Django 2.1.7 on 2019-03-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass_sheet', '0009_auto_20190311_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sasssheetmap',
            name='api_columns',
            field=models.ManyToManyField(to='sass_sheet.ApiField'),
        ),
    ]
